### ISSUE TITLE
exec (or x) should be set as command

### ISSUE THREAD

**Issue by gbprod** [the-mikedavis/tree-sitter-git-rebase#1]
Hello!

I encounter what I believe to be an inconsistency trying to use this parser with Neovim.

The `exec` command is not parsed as `command` but as an anonymous token.

Maybe we should do that : 

```javascript
    _exec_operation: ($) => seq(alias(choice("x", "exec"), $.command), $.message),
```

Thanks for your feedback

**Comment by the-mikedavis** [comment]
Good catch, thanks for pointing this out! I pushed a commit with that alias 👍

**Comment by gbprod** [comment]
Thanks !!!
